/* AUTO-GENERATED by scripts/inject-public-env.mjs — do not edit */
export const INLINED_PUBLIC_ENV = {
  NEXT_PUBLIC_API_BASE: "https://api.useantara.com",
  NEXT_PUBLIC_APP_ID: "d7c3acc1-c16e-4044-89bd-6da49fb84078",
  NEXT_PUBLIC_REDIRECT_URI: "http://localhost:3000/dashboard",
} as const;
